<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>FingerprintBridge</RootNamespace>
    <AssemblyName>FingerprintBridge</AssemblyName>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DPFPDevNET">
      <HintPath>C:\Program Files\HID Global\Authentication Device Client\One Touch SDK\.NET\Bin\DPFPDevNET.dll</HintPath>
    </Reference>
    <Reference Include="DPFPEngNET">
      <HintPath>C:\Program Files\HID Global\Authentication Device Client\One Touch SDK\.NET\Bin\DPFPEngNET.dll</HintPath>
    </Reference>
    <Reference Include="DPFPShrNET">
      <HintPath>C:\Program Files\HID Global\Authentication Device Client\One Touch SDK\.NET\Bin\DPFPShrNET.dll</HintPath>
    </Reference>
    <Reference Include="DPFPVerNET">
      <HintPath>C:\Program Files\HID Global\Authentication Device Client\One Touch SDK\.NET\Bin\DPFPVerNET.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
