<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>FingerprintEnrollUi</RootNamespace>
    <AssemblyName>FingerprintEnrollUi</AssemblyName>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DPFPGuiNET">
      <HintPath>C:\Program Files\HID Global\Authentication Device Client\One Touch SDK\.NET\Bin\DPFPGuiNET.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DPFPShrNET">
      <HintPath>C:\Program Files\HID Global\Authentication Device Client\One Touch SDK\.NET\Bin\DPFPShrNET.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DPFPVerNET">
      <HintPath>C:\Program Files\HID Global\Authentication Device Client\One Touch SDK\.NET\Bin\DPFPVerNET.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
